server:
  port: 8082
spring:
  application:
    name: tysoft-gateway-service
  cloud:
    gateway:
      routes:
        - id: web
          uri: http://127.0.0.1:8088/web/
          predicates:
            - Path=/web/**
eureka:
  instance:
    prefer-ip-address: true #使用服务的id地址注册
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true