server:
  port: 8083
  servlet:
      context-path: /auth
spring:
  application:
    name: auth
  # 数据库默认存用户鉴权相关信息
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    jedis:
      pool:
        max-active: 600
        max-idle: 300
        max-wait: 15000ms
        min-idle: 10
  datasource:
      druid:
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 5
        max-active: 20
        max-wait: 30000
        min-idle: 5
        url: jdbc:mysql://localhost:3306/tysoft_main?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
  mybatis:
    mapper-locations: classpath*:com.tysoft.api.mapper/*Mapper.xml
    type-aliases-package: com.tysoft.entity
# 解密工具
jasypt:
  encryptor:
    password: EWRREWRERWECCCXC
    algorithm: PBEWithMD5AndDES

eureka:
  instance:
    prefer-ip-address: true #使用服务的id地址注册
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true