server:
  port: 8088

# 解密工具
jasypt:
  encryptor:
    password: EWRREWRERWECCCXC
    algorithm: PBEWithMD5AndDES

spring:
  application:
    name: 'tysoft'
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 20
      max-wait: 30000
      min-idle: 5
      url: jdbc:mysql://localhost:3306/tysoft_main?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
mybatis:
  mapper-locations: classpath*:com.tysoft.api.mapper/*Mapper.xml
  type-aliases-package: com.tysoft.entity

# 配置Security需要忽略的路径
exclude:
  path:
    - /index
    - /login/**
    - /v2/api-docs
    - /swagger-ui.html
    - /swagger-resources/**
    - /webjars/**