server:
  port: 8088
  servlet:
    context-path: /web

# 解密工具
jasypt:
  encryptor:
    password: EWRREWRERWECCCXC
    algorithm: PBEWithMD5AndDES

spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 20
      max-wait: 30000
      min-idle: 5
      url: jdbc:mysql://localhost:3306/tysoft_main?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
mybatis:
  mapper-locations: classpath*:com.tysoft.api.mapper/*Mapper.xml
  type-aliases-package: com.tysoft.entity

# 配置Security需要忽略的路径
exclude:
  path:
    - /index
    - /login/**
    - /v2/api-docs
    - /swagger-ui.html
    - /swagger-resources/**
    - /webjars/**
#日志对应的目录(本地写死)
#logBack:
#   logDir: C:\Users\zy\Desktop\LogTest\tsofyLog
#   logAppName: tysoft
#logging:
#  config: classpath:logback-spring.xml
#eureka配置
eureka:
  instance:
    prefer-ip-address: true #使用服务的id地址注册
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true
